org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Plugin Metadata
plugin_group=Hexvane
plugin_description=Hub plots and building placement for the Eternia public server
plugin_author=Hexvane
plugin_website=
plugin_main_entrypoint=com.hexvane.eterniamod.EterniaModPlugin
server_version=>=0.5.0-pre.0 <0.6.0
